numeros = (10, 20, 30, 40)
colores = tuple(["rojo", "verde", "azul"])
print("Primer numero:", numeros[0])
print("Ultimos dos numeros:", numeros[-2:])
print("Veces que aparece 20:", numeros.count(20))
print("Posicion del 30:", numeros.index(30))
punto = (5, 9)
x, y = punto
print("Coordenada X:", x)
print("Coordenada Y:", y)
persona = ("Juan", 25, ("Madrid", "España"))
print("Ciudad:", persona[2][0])